trigger:
 branches:
   include:
     - develop
pr:
 branches:
   include:
     - develop
pool: Application_agentpool

stages:
- stage: Build
  jobs:
  - job: BiomeLint
    continueOnError: true
    displayName: Biome lint(JS lint)
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'C:\Tools\biome.exe lint $(System.DefaultWorkingDirectory)/src'
  