trigger: none
pool: Application_agentpool

jobs:
- job: build_and_deploy
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        npm install
        npm run build

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
      replaceExistingArchive: true

  - task: AzureRmWebAppDeployment@5
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1 (77f3ee6c-f543-47ec-ad10-67a999f49859)'
      appType: 'webAppLinux'
      WebAppName: 'frontendtodo'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/build.zip'
      RuntimeStack: 'NODE|20-lts'
      DeploymentTypeLinux: 'oneDeploy'