trigger:
 branches:
   include:
     - develop
pr:
 branches:
   include:
     - develop
pool: Application_agentpool

stages:
- stage: Build
  jobs:
  - job: BiomeLint
    continueOnError: true
    displayName: Biome lint(JS lint)
    steps:
    - task: PowerShell@2
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: 'C:\Tools\biome.exe lint $(System.DefaultWorkingDirectory)/src'
    - task: PowerShell@2
      continueOnError: true
      displayName: sonarqube SAST
      inputs:
        targetType: 'inline'
        script: 'sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.token=sqp_a41486bbd55d8126b7ea78965962434063d30980 -Dsonar.projectKey=Todo_application'