apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todoui
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: todoui
    spec:
      containers:
      - name: todoapp
        image: pagal-dagpf2fea2aqamc4.azurecr.io/todoui:v3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: service
spec:
  type: LoadBalancer
  selector:
    app: todoui
    
  ports: 
    - name: service-port
      port: 3200
      targetPort: 80

